<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>register_button</name>
   <tag></tag>
   <elementGuidId>09ca8cb8-939f-4dcd-a832-5fbdfe6e135e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='register-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#register-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ad8f435-b2ab-4ee4-88a0-8745418398fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc66358c-a8d3-4c16-9e86-1dad9ae9163f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register-button</value>
      <webElementGuid>31206e5f-9d6c-463d-985f-3f9044071b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_registerButton__ncSav transition-250ms w-100 btn btn-primary</value>
      <webElementGuid>533d9cc5-635d-4fd5-b615-633a885ccb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>ca7d8be9-0f25-4fd7-8c30-84ba5e496213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-button&quot;)</value>
      <webElementGuid>762d1111-97ae-4202-9cd5-c73a55a025b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='register-button']</value>
      <webElementGuid>37dc9ab0-6209-4658-a1cf-072e31417f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'register-button' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>b67ef1e6-b313-4a10-bd32-6efc6534623d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
